defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: assets/img/noslackday-og-image.png

plugins:
  - jekyll-seo-tag

title: Get a taste of productivity back!

url: https://www.noslackday.org
canonical_url: https://www.noslackday.org

description: Turn off Slack for a day on August 26th.

twitter:
  username: noslackday
  card: summary

logo: assets/img/noslackday-og-image.png

exclude:
  - _sass/node_modules

seo:
  type: NewsArticle

host: 0.0.0.0
