defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag

title: Get a taste of productivity back!

description: Turn off Slack for a day on August 26th.

twitter:
  username: noslackday
  card: summary

logo: /apple-touch-icon.png

exclude:
  - _sass/node_modules

host: 0.0.0.0
